### ISSUE TITLE
caltech.edu is down

### ISSUE THREAD

**Issue by FelizCoder** [zach401/acnportal#107]
The [Caltech](https://ev.caltech.edu/) Webpage seems to be down since at least yesterday. API calls are not possible.

**Comment by mhassouna95** [comment]
Can also confirm!

**Comment by Marceau-stack** [comment]
The webpage seems still to be unavailable.

**Comment by zach401** [comment]
The site/api should be back online now. I apologize for the delay!

We are still having some issues with the web interface. In the mean time, you can use this Colab to download sessions in CSV or JSON format. https://colab.research.google.com/drive/1UPvurai0Wj2yvmZ3aUqHn3tdQvRWjlnO?usp=sharing
