### ISSUE TITLE
Automated continuous integration

### ISSUE THREAD

**Issue by sunash** [zach401/acnportal#12]
## Issue
Currently we have unit tests for individual parts of the simulator, but no integration tests to ensure different components of the simulator interact correctly

## Ideas
* Use the tutorial as an integration test
* Write run method so that internal state can be readily accessed
* Automatic tests on github (eg TravisCI)
* Tests with known behavior (e.g. deterministic algorithm, specific event queues, etc.)

**Comment by zach401** [comment]
@sunash This is set up, right? Should we close the issue?

**Comment by sunash** [comment]
This is set up with Travis CI. Recently Travis had a bug in which Travis check results did not show up on pull requests, but this seems to be fixed now.

**Comment by sunash** [comment]
We'll reopen if the issue comes up again.
