### ISSUE TITLE
Convert pilot_signals and charging_rates to Numpy Arrays or Pandas DataFrames

### ISSUE THREAD

**Issue by zach401** [zach401/acnportal#5]
## Issue
Initially I implemented pilot_signals and charging_rates as dictionaries of lists. However, this is highly inefficient as most operations can be vectorized for major speedups. In fact we already convert these lists into matrices in multiple functions such as constraint_current() within ConstraintSet.

## Decision
We will need to decide if whether to use np arrays or pd DataFrames for this task. Arrays will likely be a bit faster and use less memory, but DataFrames have the benefit of naming rows directly (helpful for keeping track of which EVSE each row corresponds to and the ability to use time as the index, which may be helpful. 

Also, for fixed duration experiments we can allocate the array size at the beginning of the simulation, however if we want to support interactive simulations, we need to support dynamic resizing of these arrays. 

## To-Do First
Before undertaking this issue, tests should be written for all methods which interact with pilot_signals and charging_rates.

**Comment by sunash** [comment]
We decided to use pandas DataFrames to represent these fields, as these can contain information about EVSE station_id and so are insensitive to ordering. In terms of memory, longer simulations will take on the order of megabytes of space (worst case we can write schedules to file, see issue #7 ). If speed with DataFrames ends up being too slow, conversion to numpy arrays shouldn't be too hard.
