### ISSUE TITLE
QST: Encounter with error for the first example

### ISSUE THREAD

**Issue by JY231** [zach401/acnportal#73]
Hi Zach,

I was trying to run the first tutorial after installing the packages. But I encountered with the following error for this line.(**from acnportal import acnsim**)

ImportError: cannot import name 'stringify_path' from 'pandas.io.common' (C:\Users\jubai\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\common.py)

```python
# Your code here, if applicable

```

**Comment by zach401** [comment]
What version of pandas are you running? I assume this is a pandas version issue. We should probably enforce a minimum version number on install. 

Also, are you running the Jupiter notebook or script version?

I can confirm the tutorial 1 script runs on my machine with pandas==1.1.0.

**Comment by zach401** [comment]
I was able to recreate the issue using pandas==0.25.3, the last release before 1.0.0. 

The solution is to upgrade pandas to >=1.0.0. I believe there were some breaking changes with the 1.0 release. 

I will update the setup.py script to require pandas >=1.0.0.

**Comment by JY231** [comment]
Thanks a lot, Zach. Yes, my pandas version was outdated. It works fine after the update.

**Comment by zach401** [comment]
Awesome! Glad it works for you. I have updated the setup.py script so that it will enforce this version dependency in the future. Thanks for bringing this to our attention! 

Zach
